plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

custom:
  serverless-offline:
    httpPort: 3000
    websocketPort: 3001
    lambdaPort: 3002
    useChildProcesses: true

org: vegetationbush
app: serverless
service: backend

functions:
  leaderboard:
    handler: src/handlers/leaderboard.handler
    events:
      - httpApi:
          path: /leaderboard
          method: get
      - httpApi:
          path: /leaderboard
          method: post